// Code generated by go-swagger; DO NOT EDIT.

package secscan

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new secscan API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for secscan API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	GetRepoImageSecurity(params *GetRepoImageSecurityParams, authInfo runtime.ClientAuthInfoWriter) (*GetRepoImageSecurityOK, error)

	GetRepoManifestSecurity(params *GetRepoManifestSecurityParams, authInfo runtime.ClientAuthInfoWriter) (*GetRepoManifestSecurityOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  GetRepoImageSecurity Fetches the features and vulnerabilities (if any) for a repository image.
*/
func (a *Client) GetRepoImageSecurity(params *GetRepoImageSecurityParams, authInfo runtime.ClientAuthInfoWriter) (*GetRepoImageSecurityOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRepoImageSecurityParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getRepoImageSecurity",
		Method:             "GET",
		PathPattern:        "/api/v1/repository/{repository}/image/{imageid}/security",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetRepoImageSecurityReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRepoImageSecurityOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getRepoImageSecurity: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetRepoManifestSecurity get repo manifest security API
*/
func (a *Client) GetRepoManifestSecurity(params *GetRepoManifestSecurityParams, authInfo runtime.ClientAuthInfoWriter) (*GetRepoManifestSecurityOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRepoManifestSecurityParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getRepoManifestSecurity",
		Method:             "GET",
		PathPattern:        "/api/v1/repository/{repository}/manifest/{manifestref}/security",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetRepoManifestSecurityReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetRepoManifestSecurityOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getRepoManifestSecurity: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
