// Code generated by go-swagger; DO NOT EDIT.

package organization

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/clamoriniere/go-quay/models"
)

// GetOrganizationCollaboratorsReader is a Reader for the GetOrganizationCollaborators structure.
type GetOrganizationCollaboratorsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetOrganizationCollaboratorsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetOrganizationCollaboratorsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetOrganizationCollaboratorsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetOrganizationCollaboratorsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewGetOrganizationCollaboratorsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetOrganizationCollaboratorsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetOrganizationCollaboratorsOK creates a GetOrganizationCollaboratorsOK with default headers values
func NewGetOrganizationCollaboratorsOK() *GetOrganizationCollaboratorsOK {
	return &GetOrganizationCollaboratorsOK{}
}

/*GetOrganizationCollaboratorsOK handles this case with default header values.

Successful invocation
*/
type GetOrganizationCollaboratorsOK struct {
}

func (o *GetOrganizationCollaboratorsOK) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/collaborators][%d] getOrganizationCollaboratorsOK ", 200)
}

func (o *GetOrganizationCollaboratorsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetOrganizationCollaboratorsBadRequest creates a GetOrganizationCollaboratorsBadRequest with default headers values
func NewGetOrganizationCollaboratorsBadRequest() *GetOrganizationCollaboratorsBadRequest {
	return &GetOrganizationCollaboratorsBadRequest{}
}

/*GetOrganizationCollaboratorsBadRequest handles this case with default header values.

Bad Request
*/
type GetOrganizationCollaboratorsBadRequest struct {
	Payload *models.APIError
}

func (o *GetOrganizationCollaboratorsBadRequest) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/collaborators][%d] getOrganizationCollaboratorsBadRequest  %+v", 400, o.Payload)
}

func (o *GetOrganizationCollaboratorsBadRequest) GetPayload() *models.APIError {
	return o.Payload
}

func (o *GetOrganizationCollaboratorsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationCollaboratorsUnauthorized creates a GetOrganizationCollaboratorsUnauthorized with default headers values
func NewGetOrganizationCollaboratorsUnauthorized() *GetOrganizationCollaboratorsUnauthorized {
	return &GetOrganizationCollaboratorsUnauthorized{}
}

/*GetOrganizationCollaboratorsUnauthorized handles this case with default header values.

Session required
*/
type GetOrganizationCollaboratorsUnauthorized struct {
	Payload *models.APIError
}

func (o *GetOrganizationCollaboratorsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/collaborators][%d] getOrganizationCollaboratorsUnauthorized  %+v", 401, o.Payload)
}

func (o *GetOrganizationCollaboratorsUnauthorized) GetPayload() *models.APIError {
	return o.Payload
}

func (o *GetOrganizationCollaboratorsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationCollaboratorsForbidden creates a GetOrganizationCollaboratorsForbidden with default headers values
func NewGetOrganizationCollaboratorsForbidden() *GetOrganizationCollaboratorsForbidden {
	return &GetOrganizationCollaboratorsForbidden{}
}

/*GetOrganizationCollaboratorsForbidden handles this case with default header values.

Unauthorized access
*/
type GetOrganizationCollaboratorsForbidden struct {
	Payload *models.APIError
}

func (o *GetOrganizationCollaboratorsForbidden) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/collaborators][%d] getOrganizationCollaboratorsForbidden  %+v", 403, o.Payload)
}

func (o *GetOrganizationCollaboratorsForbidden) GetPayload() *models.APIError {
	return o.Payload
}

func (o *GetOrganizationCollaboratorsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetOrganizationCollaboratorsNotFound creates a GetOrganizationCollaboratorsNotFound with default headers values
func NewGetOrganizationCollaboratorsNotFound() *GetOrganizationCollaboratorsNotFound {
	return &GetOrganizationCollaboratorsNotFound{}
}

/*GetOrganizationCollaboratorsNotFound handles this case with default header values.

Not found
*/
type GetOrganizationCollaboratorsNotFound struct {
	Payload *models.APIError
}

func (o *GetOrganizationCollaboratorsNotFound) Error() string {
	return fmt.Sprintf("[GET /api/v1/organization/{orgname}/collaborators][%d] getOrganizationCollaboratorsNotFound  %+v", 404, o.Payload)
}

func (o *GetOrganizationCollaboratorsNotFound) GetPayload() *models.APIError {
	return o.Payload
}

func (o *GetOrganizationCollaboratorsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.APIError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
