// Code generated by go-swagger; DO NOT EDIT.

package robot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetUserRobotsParams creates a new GetUserRobotsParams object
// with the default values initialized.
func NewGetUserRobotsParams() *GetUserRobotsParams {
	var ()
	return &GetUserRobotsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetUserRobotsParamsWithTimeout creates a new GetUserRobotsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetUserRobotsParamsWithTimeout(timeout time.Duration) *GetUserRobotsParams {
	var ()
	return &GetUserRobotsParams{

		timeout: timeout,
	}
}

// NewGetUserRobotsParamsWithContext creates a new GetUserRobotsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetUserRobotsParamsWithContext(ctx context.Context) *GetUserRobotsParams {
	var ()
	return &GetUserRobotsParams{

		Context: ctx,
	}
}

// NewGetUserRobotsParamsWithHTTPClient creates a new GetUserRobotsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetUserRobotsParamsWithHTTPClient(client *http.Client) *GetUserRobotsParams {
	var ()
	return &GetUserRobotsParams{
		HTTPClient: client,
	}
}

/*GetUserRobotsParams contains all the parameters to send to the API endpoint
for the get user robots operation typically these are written to a http.Request
*/
type GetUserRobotsParams struct {

	/*Limit
	  If specified, the number of robots to return.

	*/
	Limit *int64
	/*Permissions
	  Whether to include repositories and teams in which the robots have permission.

	*/
	Permissions *bool
	/*Token
	  If false, the robot's token is not returned.

	*/
	Token *bool

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get user robots params
func (o *GetUserRobotsParams) WithTimeout(timeout time.Duration) *GetUserRobotsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get user robots params
func (o *GetUserRobotsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get user robots params
func (o *GetUserRobotsParams) WithContext(ctx context.Context) *GetUserRobotsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get user robots params
func (o *GetUserRobotsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get user robots params
func (o *GetUserRobotsParams) WithHTTPClient(client *http.Client) *GetUserRobotsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get user robots params
func (o *GetUserRobotsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLimit adds the limit to the get user robots params
func (o *GetUserRobotsParams) WithLimit(limit *int64) *GetUserRobotsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get user robots params
func (o *GetUserRobotsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithPermissions adds the permissions to the get user robots params
func (o *GetUserRobotsParams) WithPermissions(permissions *bool) *GetUserRobotsParams {
	o.SetPermissions(permissions)
	return o
}

// SetPermissions adds the permissions to the get user robots params
func (o *GetUserRobotsParams) SetPermissions(permissions *bool) {
	o.Permissions = permissions
}

// WithToken adds the token to the get user robots params
func (o *GetUserRobotsParams) WithToken(token *bool) *GetUserRobotsParams {
	o.SetToken(token)
	return o
}

// SetToken adds the token to the get user robots params
func (o *GetUserRobotsParams) SetToken(token *bool) {
	o.Token = token
}

// WriteToRequest writes these params to a swagger request
func (o *GetUserRobotsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Permissions != nil {

		// query param permissions
		var qrPermissions bool
		if o.Permissions != nil {
			qrPermissions = *o.Permissions
		}
		qPermissions := swag.FormatBool(qrPermissions)
		if qPermissions != "" {
			if err := r.SetQueryParam("permissions", qPermissions); err != nil {
				return err
			}
		}

	}

	if o.Token != nil {

		// query param token
		var qrToken bool
		if o.Token != nil {
			qrToken = *o.Token
		}
		qToken := swag.FormatBool(qrToken)
		if qToken != "" {
			if err := r.SetQueryParam("token", qToken); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
