// Code generated by go-swagger; DO NOT EDIT.

package robot

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new robot API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for robot API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	CreateOrgRobot(params *CreateOrgRobotParams, authInfo runtime.ClientAuthInfoWriter) (*CreateOrgRobotOK, error)

	CreateUserRobot(params *CreateUserRobotParams, authInfo runtime.ClientAuthInfoWriter) (*CreateUserRobotOK, error)

	DeleteOrgRobot(params *DeleteOrgRobotParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteOrgRobotNoContent, error)

	DeleteUserRobot(params *DeleteUserRobotParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteUserRobotNoContent, error)

	GetOrgRobot(params *GetOrgRobotParams, authInfo runtime.ClientAuthInfoWriter) (*GetOrgRobotOK, error)

	GetOrgRobotPermissions(params *GetOrgRobotPermissionsParams, authInfo runtime.ClientAuthInfoWriter) (*GetOrgRobotPermissionsOK, error)

	GetOrgRobots(params *GetOrgRobotsParams, authInfo runtime.ClientAuthInfoWriter) (*GetOrgRobotsOK, error)

	GetUserRobot(params *GetUserRobotParams, authInfo runtime.ClientAuthInfoWriter) (*GetUserRobotOK, error)

	GetUserRobotPermissions(params *GetUserRobotPermissionsParams, authInfo runtime.ClientAuthInfoWriter) (*GetUserRobotPermissionsOK, error)

	GetUserRobots(params *GetUserRobotsParams, authInfo runtime.ClientAuthInfoWriter) (*GetUserRobotsOK, error)

	RegenerateOrgRobotToken(params *RegenerateOrgRobotTokenParams, authInfo runtime.ClientAuthInfoWriter) (*RegenerateOrgRobotTokenCreated, error)

	RegenerateUserRobotToken(params *RegenerateUserRobotTokenParams, authInfo runtime.ClientAuthInfoWriter) (*RegenerateUserRobotTokenCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  CreateOrgRobot Create a new robot in the organization.
*/
func (a *Client) CreateOrgRobot(params *CreateOrgRobotParams, authInfo runtime.ClientAuthInfoWriter) (*CreateOrgRobotOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateOrgRobotParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createOrgRobot",
		Method:             "PUT",
		PathPattern:        "/api/v1/organization/{orgname}/robots/{robot_shortname}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateOrgRobotReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateOrgRobotOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createOrgRobot: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  CreateUserRobot Create a new user robot with the specified name.
*/
func (a *Client) CreateUserRobot(params *CreateUserRobotParams, authInfo runtime.ClientAuthInfoWriter) (*CreateUserRobotOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewCreateUserRobotParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "createUserRobot",
		Method:             "PUT",
		PathPattern:        "/api/v1/user/robots/{robot_shortname}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &CreateUserRobotReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*CreateUserRobotOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for createUserRobot: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DeleteOrgRobot Delete an existing organization robot.
*/
func (a *Client) DeleteOrgRobot(params *DeleteOrgRobotParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteOrgRobotNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteOrgRobotParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteOrgRobot",
		Method:             "DELETE",
		PathPattern:        "/api/v1/organization/{orgname}/robots/{robot_shortname}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteOrgRobotReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteOrgRobotNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteOrgRobot: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DeleteUserRobot Delete an existing robot.
*/
func (a *Client) DeleteUserRobot(params *DeleteUserRobotParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteUserRobotNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteUserRobotParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteUserRobot",
		Method:             "DELETE",
		PathPattern:        "/api/v1/user/robots/{robot_shortname}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteUserRobotReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteUserRobotNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteUserRobot: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetOrgRobot Returns the organization's robot with the specified name.
*/
func (a *Client) GetOrgRobot(params *GetOrgRobotParams, authInfo runtime.ClientAuthInfoWriter) (*GetOrgRobotOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetOrgRobotParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getOrgRobot",
		Method:             "GET",
		PathPattern:        "/api/v1/organization/{orgname}/robots/{robot_shortname}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetOrgRobotReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetOrgRobotOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getOrgRobot: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetOrgRobotPermissions Returns the list of repository permissions for the org's robot.
*/
func (a *Client) GetOrgRobotPermissions(params *GetOrgRobotPermissionsParams, authInfo runtime.ClientAuthInfoWriter) (*GetOrgRobotPermissionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetOrgRobotPermissionsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getOrgRobotPermissions",
		Method:             "GET",
		PathPattern:        "/api/v1/organization/{orgname}/robots/{robot_shortname}/permissions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetOrgRobotPermissionsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetOrgRobotPermissionsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getOrgRobotPermissions: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetOrgRobots List the organization's robots.
*/
func (a *Client) GetOrgRobots(params *GetOrgRobotsParams, authInfo runtime.ClientAuthInfoWriter) (*GetOrgRobotsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetOrgRobotsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getOrgRobots",
		Method:             "GET",
		PathPattern:        "/api/v1/organization/{orgname}/robots",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetOrgRobotsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetOrgRobotsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getOrgRobots: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetUserRobot Returns the user's robot with the specified name.
*/
func (a *Client) GetUserRobot(params *GetUserRobotParams, authInfo runtime.ClientAuthInfoWriter) (*GetUserRobotOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetUserRobotParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getUserRobot",
		Method:             "GET",
		PathPattern:        "/api/v1/user/robots/{robot_shortname}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetUserRobotReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetUserRobotOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getUserRobot: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetUserRobotPermissions Returns the list of repository permissions for the user's robot.
*/
func (a *Client) GetUserRobotPermissions(params *GetUserRobotPermissionsParams, authInfo runtime.ClientAuthInfoWriter) (*GetUserRobotPermissionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetUserRobotPermissionsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getUserRobotPermissions",
		Method:             "GET",
		PathPattern:        "/api/v1/user/robots/{robot_shortname}/permissions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetUserRobotPermissionsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetUserRobotPermissionsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getUserRobotPermissions: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetUserRobots List the available robots for the user.
*/
func (a *Client) GetUserRobots(params *GetUserRobotsParams, authInfo runtime.ClientAuthInfoWriter) (*GetUserRobotsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetUserRobotsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getUserRobots",
		Method:             "GET",
		PathPattern:        "/api/v1/user/robots",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetUserRobotsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetUserRobotsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getUserRobots: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  RegenerateOrgRobotToken Regenerates the token for an organization robot.
*/
func (a *Client) RegenerateOrgRobotToken(params *RegenerateOrgRobotTokenParams, authInfo runtime.ClientAuthInfoWriter) (*RegenerateOrgRobotTokenCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRegenerateOrgRobotTokenParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "regenerateOrgRobotToken",
		Method:             "POST",
		PathPattern:        "/api/v1/organization/{orgname}/robots/{robot_shortname}/regenerate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RegenerateOrgRobotTokenReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RegenerateOrgRobotTokenCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for regenerateOrgRobotToken: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  RegenerateUserRobotToken Regenerates the token for a user's robot.
*/
func (a *Client) RegenerateUserRobotToken(params *RegenerateUserRobotTokenParams, authInfo runtime.ClientAuthInfoWriter) (*RegenerateUserRobotTokenCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRegenerateUserRobotTokenParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "regenerateUserRobotToken",
		Method:             "POST",
		PathPattern:        "/api/v1/user/robots/{robot_shortname}/regenerate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RegenerateUserRobotTokenReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RegenerateUserRobotTokenCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for regenerateUserRobotToken: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
