// Code generated by go-swagger; DO NOT EDIT.

package billing

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new billing API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for billing API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	ListOrgInvoices(params *ListOrgInvoicesParams, authInfo runtime.ClientAuthInfoWriter) (*ListOrgInvoicesOK, error)

	ListPlans(params *ListPlansParams) (*ListPlansOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ListOrgInvoices List the invoices for the specified orgnaization.
*/
func (a *Client) ListOrgInvoices(params *ListOrgInvoicesParams, authInfo runtime.ClientAuthInfoWriter) (*ListOrgInvoicesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListOrgInvoicesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listOrgInvoices",
		Method:             "GET",
		PathPattern:        "/api/v1/organization/{orgname}/invoices",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListOrgInvoicesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListOrgInvoicesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listOrgInvoices: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ListPlans List the avaialble plans.
*/
func (a *Client) ListPlans(params *ListPlansParams) (*ListPlansOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListPlansParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listPlans",
		Method:             "GET",
		PathPattern:        "/api/v1/plans/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListPlansReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListPlansOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listPlans: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
