// Code generated by go-swagger; DO NOT EDIT.

package tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new tag API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for tag API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	ChangeTag(params *ChangeTagParams, authInfo runtime.ClientAuthInfoWriter) (*ChangeTagOK, error)

	DeleteFullTag(params *DeleteFullTagParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteFullTagNoContent, error)

	ListRepoTags(params *ListRepoTagsParams, authInfo runtime.ClientAuthInfoWriter) (*ListRepoTagsOK, error)

	ListTagImages(params *ListTagImagesParams, authInfo runtime.ClientAuthInfoWriter) (*ListTagImagesOK, error)

	RestoreTag(params *RestoreTagParams, authInfo runtime.ClientAuthInfoWriter) (*RestoreTagCreated, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ChangeTag Change which image a tag points to or create a new tag.
*/
func (a *Client) ChangeTag(params *ChangeTagParams, authInfo runtime.ClientAuthInfoWriter) (*ChangeTagOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewChangeTagParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "changeTag",
		Method:             "PUT",
		PathPattern:        "/api/v1/repository/{repository}/tag/{tag}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ChangeTagReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ChangeTagOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for changeTag: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  DeleteFullTag Delete the specified repository tag.
*/
func (a *Client) DeleteFullTag(params *DeleteFullTagParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteFullTagNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteFullTagParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "deleteFullTag",
		Method:             "DELETE",
		PathPattern:        "/api/v1/repository/{repository}/tag/{tag}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteFullTagReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteFullTagNoContent)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for deleteFullTag: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ListRepoTags list repo tags API
*/
func (a *Client) ListRepoTags(params *ListRepoTagsParams, authInfo runtime.ClientAuthInfoWriter) (*ListRepoTagsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListRepoTagsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listRepoTags",
		Method:             "GET",
		PathPattern:        "/api/v1/repository/{repository}/tag/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListRepoTagsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListRepoTagsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listRepoTags: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ListTagImages List the images for the specified repository tag.
*/
func (a *Client) ListTagImages(params *ListTagImagesParams, authInfo runtime.ClientAuthInfoWriter) (*ListTagImagesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListTagImagesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "listTagImages",
		Method:             "GET",
		PathPattern:        "/api/v1/repository/{repository}/tag/{tag}/images",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListTagImagesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ListTagImagesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for listTagImages: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  RestoreTag Restores a repository tag back to a previous image in the repository.
*/
func (a *Client) RestoreTag(params *RestoreTagParams, authInfo runtime.ClientAuthInfoWriter) (*RestoreTagCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewRestoreTagParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "restoreTag",
		Method:             "POST",
		PathPattern:        "/api/v1/repository/{repository}/tag/{tag}/restore",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &RestoreTagReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*RestoreTagCreated)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for restoreTag: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
