// Code generated by go-swagger; DO NOT EDIT.

package search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new search API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for search API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	ConductRepoSearch(params *ConductRepoSearchParams) (*ConductRepoSearchOK, error)

	ConductSearch(params *ConductSearchParams, authInfo runtime.ClientAuthInfoWriter) (*ConductSearchOK, error)

	GetMatchingEntities(params *GetMatchingEntitiesParams) (*GetMatchingEntitiesOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  ConductRepoSearch Get a list of apps and repositories that match the specified query.
*/
func (a *Client) ConductRepoSearch(params *ConductRepoSearchParams) (*ConductRepoSearchOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewConductRepoSearchParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "conductRepoSearch",
		Method:             "GET",
		PathPattern:        "/api/v1/find/repositories",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ConductRepoSearchReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ConductRepoSearchOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for conductRepoSearch: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  ConductSearch Get a list of entities and resources that match the specified query.
*/
func (a *Client) ConductSearch(params *ConductSearchParams, authInfo runtime.ClientAuthInfoWriter) (*ConductSearchOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewConductSearchParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "conductSearch",
		Method:             "GET",
		PathPattern:        "/api/v1/find/all",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ConductSearchReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*ConductSearchOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for conductSearch: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

/*
  GetMatchingEntities Get a list of entities that match the specified prefix.
*/
func (a *Client) GetMatchingEntities(params *GetMatchingEntitiesParams) (*GetMatchingEntitiesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetMatchingEntitiesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "getMatchingEntities",
		Method:             "GET",
		PathPattern:        "/api/v1/entities/{prefix}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetMatchingEntitiesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*GetMatchingEntitiesOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	// safeguard: normally, absent a default response, unknown success responses return an error above: so this is a codegen issue
	msg := fmt.Sprintf("unexpected success response for getMatchingEntities: API contract not enforced by server. Client expected to get an error, but got: %T", result)
	panic(msg)
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
