// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ChangeTag Makes changes to a specific tag
//
// swagger:model ChangeTag
type ChangeTag struct {

	// (If specified) The expiration for the image
	Expiration float64 `json:"expiration,omitempty"`

	// (Deprecated: Use `manifest_digest`) Image to which the tag should point.
	Image string `json:"image,omitempty"`

	// (If specified) The manifest digest to which the tag should point
	ManifestDigest string `json:"manifest_digest,omitempty"`
}

// Validate validates this change tag
func (m *ChangeTag) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChangeTag) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChangeTag) UnmarshalBinary(b []byte) error {
	var res ChangeTag
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
