// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RestoreTag Restores a tag to a specific image
//
// swagger:model RestoreTag
type RestoreTag struct {

	// (Deprecated: use `manifest_digest`) Image to which the tag should point
	Image string `json:"image,omitempty"`

	// If specified, the manifest digest that should be used
	ManifestDigest string `json:"manifest_digest,omitempty"`
}

// Validate validates this restore tag
func (m *RestoreTag) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RestoreTag) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RestoreTag) UnmarshalBinary(b []byte) error {
	var res RestoreTag
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
